apiVersion: v1
kind: Service

metadata:
  name: masterbikes-service

spec:
  selector:
    app: masterbikes-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: LoadBalancer